import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"
import { Geist, Geist_Mono } from "next/font/google";
import { AI } from "@/actions/index";
import { GridPattern } from "@/components/magicui/grid-pattern";
import Providers from "@/utils/providers";
import { cn } from "@/lib/utils";


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AI>
        <Providers>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <GridPattern
            width={20}
            height={20}
            x={-1}
            y={-1}
            className={cn(
              "[mask-image:linear-gradient(to_bottom_right,white,transparent,transparent)]"
            )}
          />
            {children}
          </body>
          <Toaster />
        </Providers>
      </AI>
    </html>
  );
}
